# Generated by Django 4.2.2 on 2023-06-19 15:20

from django.db import migrations, models
import url_shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField()),
                ('hash', models.CharField(default=url_shortener.models.generate_hash, max_length=8)),
            ],
        ),
    ]
